services:
  # --- Backend Service ---
  - type: web
    name: zoom-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --app-dir app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zoom-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: zoom-db
    plan: free